// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcIihp9qIJWH1m-2VSRUKKfWmERf0i770',
    appId: '1:526901478982:web:c2a90c06e2f9d20cd32c47',
    messagingSenderId: '526901478982',
    projectId: 'score-record-flutter-app',
    authDomain: 'score-record-flutter-app.firebaseapp.com',
    storageBucket: 'score-record-flutter-app.appspot.com',
    measurementId: 'G-YRY2S5V1Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgyiYPs9xsSCXMlN-CrsgoaKxiTMV8cFA',
    appId: '1:526901478982:android:841f852f739d9814d32c47',
    messagingSenderId: '526901478982',
    projectId: 'score-record-flutter-app',
    storageBucket: 'score-record-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvOs-FkVEJXL-VlHdKNYNoigVwbmTQBkQ',
    appId: '1:526901478982:ios:fbf12022202c459ad32c47',
    messagingSenderId: '526901478982',
    projectId: 'score-record-flutter-app',
    storageBucket: 'score-record-flutter-app.appspot.com',
    iosClientId: '526901478982-7tqao8ofoklh7jqiu5bmf3senpqfg9s6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvOs-FkVEJXL-VlHdKNYNoigVwbmTQBkQ',
    appId: '1:526901478982:ios:fbf12022202c459ad32c47',
    messagingSenderId: '526901478982',
    projectId: 'score-record-flutter-app',
    storageBucket: 'score-record-flutter-app.appspot.com',
    iosClientId: '526901478982-7tqao8ofoklh7jqiu5bmf3senpqfg9s6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
